name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: galtspace/node-test-runner:0.5.10
    steps:
    - uses: actions/checkout@v1
    - name: Install ssh key for private repos
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        /usr/bin/git ls-remote -h -t ssh://git@github.com/galtproject/galtproject-multisig.git

    - name: Install dependencies
      run: |
        /usr/bin/git ls-remote -h -t ssh://git@github.com/galtproject/galtproject-multisig.git
        npm install

    - name: Run Tests
      run: npm run eslint && npm run ethlint && npm run compile && node scripts/checkContractSize.js && npm run test
